Eliminasi Gauss

In [1]:
import numpy as np

A = np.array([[1,2,3,5],
             [2,5,3,3],
             [1,0,8,17]])

print("Matriks")
print("A = ", A)

n = len(A)
m = np.zeros((n,n))
for i in range (0,n):
  for j in range (i+1,n):
    m[j][i] = A[j][i]
    s = m[j][i]
    for k in range (0, n+1):
      A[j][k] = A[j][k] - s * A[i][k]
print('\n')
print("Matriks Eselon Baris")
print(A)

x = np.zeros((n, 1))
x[n-1][0] = A[n-1][n] / A[n-1][n-1]
for i in range (n-2, -1, -1):
  s = 0
  for j in range (i+1, n):
    s = s +A[i][j] * x[j][0]
    x[i][0] = (A[i][n] - s) / A[i][i]

print("\nSolusi")
print(x)

Matriks
A =  [[ 1  2  3  5]
 [ 2  5  3  3]
 [ 1  0  8 17]]


Matriks Eselon Baris
[[ 1  2  3  5]
 [ 0  1 -3 -7]
 [ 0  0 -1 -2]]

Solusi
[[ 1.]
 [-1.]
 [ 2.]]


Eliminasi Gauss Jordan

In [ ]:
import numpy as np

A = np.array([[1,2,3,5],
             [2,5,3,3],
             [1,0,8,17]])
print(A)
n = len (A)
x = np.zeros(n)

for k in range (n):
  pivot = A[k][k]
  A[k] = A[k]/pivot
  #print (A)
  for i in range (n):
    if i == k:continue
    factor = A[i][k]
    for j in range (k, n+1):
      A[i][j] = A[i][j] - (A[k][j] * factor)
    print ('\n')
    print(A)

x= A[:,n]
print ('\nSolusi')
print(x)

[[ 1  2  3  5]
 [ 2  5  3  3]
 [ 1  0  8 17]]


[[ 1  2  3  5]
 [ 0  1 -3 -7]
 [ 1  0  8 17]]


[[ 1  2  3  5]
 [ 0  1 -3 -7]
 [ 0 -2  5 12]]


[[ 1  0  9 19]
 [ 0  1 -3 -7]
 [ 0 -2  5 12]]


[[ 1  0  9 19]
 [ 0  1 -3 -7]
 [ 0  0 -1 -2]]


[[ 1  0  0  1]
 [ 0  1 -3 -7]
 [ 0  0  1  2]]


[[ 1  0  0  1]
 [ 0  1  0 -1]
 [ 0  0  1  2]]

Solusi
[ 1 -1  2]


Dekomposisi LU

In [ ]:
import numpy as np
import scipy.linalg as lg

A = np.array([[1,2,3,5],
             [2,5,3,3],
             [1,0,8,17]])
print("A: ")
print (A)

P, L, U = lg.lu(A)
print("L: ")
print(L)
print("U: ")
print(U)

A: 
[[ 1  2  3  5]
 [ 2  5  3  3]
 [ 1  0  8 17]]
L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.2 1. ]]
U: 
[[ 2.   5.   3.   3. ]
 [ 0.  -2.5  6.5 15.5]
 [ 0.   0.   0.2  0.4]]
